name: "Push to Artifactory"
description: "Pushes an application WAR file to Artifactory, so it can be tested"
inputs:
  artifactory-repository:
    description: "The repository to push WAR to"
    required: true
  github-artifact-name:
    description: "Name of the GitHub actions artifact"
    required: true
  artifactory-artifact-name:
    description: "Name of the artifact when uploaded to Artifactory"

runs:
  using: "composite"
  steps:
    - name: Download WAR artifact
      uses: actions/download-artifact@v8
      with:
        name: ${{ inputs.artifact-name }}
        path: ./war-to-publish

